parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

    database_driver: pdo_pgsql
    database_host: 192.168.33.10
    database_port: ~
    database_name: hero-hr
    database_user: postgres
    database_password: ~
    database_path: ~
